### PR TITLE
Update cronjob.yaml to optionally support 'nodeSelector:' and 'tolerations:'

### PR DESCRIPTION
**Pull request by mwestphall**

### CODE REVIEW

**Comment by rptaylor** [comment]
@mwestphall Nice, thanks!  
These configurables are the same as others that are currently under the `cronjob` section, e.g. `.Values.cronjob.priorityClassName`. IMO that makes it more specifically scoped and accurately described than a top-level variable (also what if e.g. there are other things running beside just the cron job in some future architecture).

I don't have a strong preference though. Is this something Brian touched on in a previous discussion?  I could go the other way if there is a reason for it but we should try to move toward consistency one way or another.

Anyway whatever the name of the value is can you add a line in the README please?

**Review by brianhlin — COMMENTED** [review]
> These configurables are the same as others that are currently under the cronjob section, e.g. .Values.cronjob.priorityClassName. IMO that makes it more specifically scoped and accurately described than a top-level variable (also what if e.g. there are other things running beside just the cron job in some future architecture).

I think this makes sense. In addition to adding this to the README, we should add commented out entries to https://github.com/rptaylor/kapel/blob/master/chart/values.yaml#L4 along with a comment noting that it's optional config

**Comment by mwestphall** [comment]
@rptaylor I moved the nodeSelector/tolerations under the cronjob object and updated the readme

**Review by rptaylor — APPROVED** [review]
Nice

**Pull request merged**
